spine-tools/SpineOpt.jl

src/objective/renewable_curtailment_costs.jl
availability factor had to be replaced with unit_conv_cap_to_flow
=> #191 fixing bug

docs/src/concept_reference/output.md, docs/src/concept_reference/unit_constraint.md, docs/src/concept_reference/unit_flow_coefficient.md
There is a note in `output.md` that needs some toughts.
=> Hjy documentation

Project.toml, src/constraints/constraint_unit_flow_capacity.jl, test/runtests.jl
Revisions and fixes to the unit tests after changes to SpineInterface 0.6.2
=> Unit test revisions

src/run_spineopt.jl, src/util/postprocess_results.jl
=> Load solver packages into the Main module

src/constraints/constraint_connection_intact_flow_ptdf.jl, src/data_structure/preprocess_data_structure.jl, test/util/postprocess_results.jl
=> Force ptdf to zero if conn avail factor is zero

src/constraints/constraint_connection_flow_lodf.jl, src/util/postprocess_results.jl, test/util/postprocess_results.jl
=> Skip lodf if reporting contingency is binding

src/data_structure/temporal_structure.jl, src/run_spineopt_benders.jl, src/run_spineopt_standard.jl
=> Introduce dry-run to check data for the last window

src/run_spineopt_standard.jl, src/util/misc.jl, test/run_spineopt.jl
=> Use CPLEX internal api to calculate duals more directly

src/data_structure/temporal_structure.jl, src/run_spineopt_standard.jl
=> Faster last window check

src/objective/renewable_curtailment_costs.jl, src/run_spineopt_standard.jl
=> Check if model has duals before interrogating with CPLEX

src/constraints/constraint_user_constraint.jl, test/constraints/constraint_connection.jl, test/constraints/constraint_unit.jl, test/constraints/constraint_user_constraint.jl
=> Scale rhs of user constraint by the duration of the time slice

README.md, src/constraints/constraint_connection_flow_lodf.jl, src/constraints/constraint_user_constraint.jl, src/objective/renewable_curtailment_costs.jl, src/run_spineopt_standard.jl, test/constraints/constraint_connection.jl, test/constraints/constraint_unit.jl, test/constraints/constraint_user_constraint.jl, test/run_spineopt.jl
- [x ] Documentation is up-to-date
- [x ] Release notes have been updated
- [x ] Unit tests have been added/updated accordingly
- [x ] Code has been formatted nicely
- [x ] Unit tests pass
=> catch up with latest master

src/constraints/constraint_connection_flow_lodf.jl, src/data_structure/postprocess_results.jl, test/data_structure/postprocess_results.jl
=> Introduce contingency_is_binding_ratio

Project.toml, src/data_structure/preprocess_data_structure.jl
To prevent access to private fields
=> Use add_object/relationship_parameter_values more

Project.toml, src/data_structure/preprocess_data_structure.jl
=> merge from the latest master

Project.toml, src/data_structure/preprocess_data_structure.jl, test/data_structure/preprocess_data_structure.jl
=> Use new SpineInterface API in preprocessing

Project.toml, src/data_structure/preprocess_data_structure.jl, test/data_structure/preprocess_data_structure.jl
=> Fetch the latest master

Project.toml, docs/mkdocs.yml, src/SpineOpt.jl, src/run_spineopt.jl
=> merge from tha latest master

src/constraints/constraint_candidate_connection_flow_lb.jl, test/constraints/constraint_connection.jl, test/constraints/constraint_node.jl, test/constraints/constraint_unit.jl
The constraint's tests were broken because another test set that came after was called the same, although it was for a different constraint.
We also use a functional approach to writing tests which makes it easier to execute some of them in isolation.
=> Fix constraint candidate connection lb

Project.toml, src/constraints/constraint_mp_any_invested_cuts.jl, src/data_structure/benders_data.jl, src/data_structure/postprocess_results.jl, src/data_structure/preprocess_data_structure.jl, src/data_structure/temporal_structure.jl, src/objective/total_costs.jl, src/run_spineopt.jl, src/run_spineopt_benders.jl, src/run_spineopt_standard.jl, src/util/misc.jl, src/variables/variable_common.jl, src/variables/variable_connections_invested_available.jl, src/variables/variable_mp_objective_lowerbound.jl, src/variables/variable_storages_invested_available.jl, src/variables/variable_units_invested_available.jl, test/constraints/constraint_connection.jl, test/constraints/constraint_unit.jl, test/data_structure/algorithm_mga_structure.jl, test/run_spineopt.jl
Improves benders and makes it work.
=> More benders fixes

docs/src/advanced_concepts/decomposition.md, src/constraints/constraint_mp_any_invested_cuts.jl, src/data_structure/benders_data.jl, src/data_structure/check_data_structure.jl, src/data_structure/preprocess_data_structure.jl, src/data_structure/temporal_structure.jl, src/run_spineopt_benders.jl, src/run_spineopt_standard.jl, src/variables/variable_connections_invested_available.jl, src/variables/variable_storages_invested_available.jl, src/variables/variable_units_invested_available.jl, test/constraints/constraint_unit.jl, test/data_structure/temporal_structure.jl, test/run_spineopt.jl
This makes benders work nicely with rolling representative periods.
=> Try and fix computation of current window for master problem

src/run_spineopt_standard.jl
=> Fix computation of reduced_cost with CPLEX

Project.toml, src/constraints/constraint_mp_any_invested_cuts.jl, src/data_structure/benders_data.jl, src/data_structure/temporal_structure.jl, src/run_spineopt_benders.jl, src/run_spineopt_standard.jl
=> Force master problem solution upon the *non* rolling subproblem too

src/data_structure/benders_data.jl, src/data_structure/temporal_structure.jl, src/objective/total_costs.jl, src/run_spineopt.jl, src/run_spineopt_benders.jl, src/run_spineopt_mga.jl, src/run_spineopt_standard.jl, test/run_spineopt.jl
If the subproblem has a lookahead, the master problem will have the same lookahead now.
=> Add lookahead time-slices to the master problem too

src/constraints/constraint_units_available.jl, src/data_structure/benders_data.jl, src/run_spineopt.jl, src/run_spineopt_standard.jl, src/util/misc.jl, test/run_spineopt.jl
=> Check result_count before interrogating the solution

src/data_structure/temporal_structure.jl
=> Let t_before_t connect time-slices across window boundaries

src/data_structure/postprocess_results.jl, src/data_structure/preprocess_data_structure.jl, src/run_spineopt_benders.jl, src/run_spineopt_standard.jl
=> Add preprocessing step to make sure required outputs are computed

CONTRIBUTING.md
Add more descriptions for new contributors based on my own experience.
Fixes #736
=> Add more descriptions for new contributers

docs/make.jl
=> Add the new tutorials to documentation

src/constraints/constraint_connection_intact_flow_ptdf.jl, src/data_structure/preprocess_data_structure.jl
=> #814 boundary flows

src/SpineOpt.jl, src/data_structure/benders_data.jl, src/data_structure/mga_data.jl, src/data_structure/temporal_structure.jl, src/run_spineopt.jl, src/run_spineopt_benders.jl, src/run_spineopt_mga.jl, src/run_spineopt_standard.jl
=> Introduce run_kernel argument to run_spineopt

docs/src/how_to/print_the_model.md, src/SpineOpt.jl
=> Update how to print the model

docs/src/advanced_concepts/ramping.md, docs/src/advanced_concepts/reserves.md, docs/src/tutorial/reserves.md
=> 827 update reserves documentation

.github/workflows/ci.yml, src/constraints/constraint_unit_flow_capacity.jl
=> update julia and python version for unit-test

docs/src/tutorial/temporal_resolution.md
Created tutorial with photos of how to create:
- Uniform temporal resolution
- Varying temporal resolution by time
- Varying temporal resolution by part of the system
Fixes #780 
- [NA] Documentation is up-to-date
=> 780 temporal resolution tutorial

docs/src/mathematical_formulation/constraints.md, src/data_structure/economic_structure.jl, src/data_structure/temporal_structure.jl, test/runtests.jl
Fixing the ci in the economic representation branch
=> Economic representation fix ci

test/data_structure/check_economic_structure.jl
=> Fix a test

test/data_structure/check_economic_structure.jl
=> Fix a few tests in "algorithm structure"

src/constraints/constraint_connection_flow_capacity.jl, test/constraints/constraint_connection.jl
Fixes #685 as per [this approach](https://github.com/spine-tools/SpineOpt.jl/issues/685#issuecomment-1929439455)
=> 685 bidirectional connection becomes unbounded

src/constraints/constraint_connection_flow_capacity.jl, src/constraints/constraint_connection_intact_flow_capacity.jl, test/constraints/constraint_connection.jl
Fixes the main issue in #685
@nnhjy if you want to implement the tighter option discussed in that same issue please go ahead after we merge this?
=> Fix connection flow capacity constraint

src/data_structure/temporal_structure.jl
=> Get rid of unused t_in_t_excl and t_overlaps_t_excl

src/constraints/constraint_common.jl, src/constraints/constraint_connection_flow_capacity.jl, src/constraints/constraint_connection_intact_flow_capacity.jl, test/constraints/constraint_connection.jl
Reverts spine-tools/SpineOpt.jl#919
=> Revert "685 bidirectional connection becomes unbounded"

.github/DISCUSSION_TEMPLATE/support.yml
Fixes #883
- [NA] Documentation is up-to-date
=> Fix Discussion YAML template

docs/Project.toml
Remove Revise from docs/Project.toml
Snuck in while changing the logo in #889
=> Remove revise from docs/Project.toml

docs/src/implementation_details/time_slices.md, docs/src/library.md, src/SpineOpt.jl, src/constraints/constraint_common.jl, src/constraints/constraint_unit_flow_capacity.jl, src/data_structure/stochastic_structure.jl, src/data_structure/temporal_structure.jl, src/run_spineopt_standard.jl
=> Revive t_in_t_excl and use for t_extreme_resolution

examples/reserves.json, examples/simple_system.json, examples/unit_commitment.json, test/run_examples.jl
I did two things:
- change the test
- run `upgrade_all.jl`; that's why there are more changes in the jsons.
Fixes #956
=> Change test `run_examples.jl`

src/constraints/constraint_unit_flow_capacity.jl, templates/spineopt_template.json, test/constraints/constraint_connection.jl, test/constraints/constraint_unit.jl
=> Introduce use_tight_compact_formulations

src/constraints/constraint_node_state_capacity.jl, src/constraints/constraint_unit_flow_capacity.jl, src/constraints/constraint_unit_state_transition.jl, src/constraints/constraint_units_available.jl, src/constraints/constraint_units_out_of_service_transition.jl, src/data_structure/preprocess_data_structure.jl, src/variables/variable_node_state.jl, src/variables/variable_unit_flow.jl, src/variables/variable_units_on.jl, src/variables/variable_units_out_of_service.jl, test/constraints/constraint_node.jl
=> Use variable bounds for unit_flow and node_state when possible

Project.toml
=> Update minimum Julia compatible version

src/data_structure/preprocess_data_structure.jl, test/constraints/constraint_connection.jl, test/data_structure/postprocess_results.jl
=> Performance: Don't use connection intact flow if no connection investments

src/constraints/constraint_common.jl, src/constraints/constraint_connection_flow_intact_flow.jl, src/constraints/constraint_ratio_out_in_connection_flow.jl, src/constraints/constraint_ratio_unit_flow.jl, src/constraints/constraint_unit_pw_heat_rate.jl
=> Optimise t_lowest_resolution_paths! for deterministic models

src/data_structure/temporal_structure.jl
=> Performance: Optimise t_extreme_resolution

src/run_spineopt.jl, src/run_spineopt_standard.jl, src/util/misc.jl
=> Write solution stats to output db

src/run_spineopt_benders.jl, src/run_spineopt_standard.jl, test/run_spineopt_benders.jl
=> Fix reporting of total costs in Benders so it sums invest. and op. costs

docs/docs_utils.jl, src/constraints/constraint_common.jl, src/constraints/constraint_connection_flow_capacity.jl, src/constraints/constraint_ramp_down.jl, src/constraints/constraint_ramp_up.jl, src/data_structure/migration.jl, src/data_structure/versions/update_investment_variable_type.jl, src/run_spineopt_standard.jl, test/constraints/constraint_connection.jl, test/data_structure/algorithm_mga_structure.jl
- Fix syntax parsing errors
- Use recommended syntax
- Fix an error in migrating parameter values
=> Use recommended syntax and formatting

src/run_spineopt_basic.jl, templates/spineopt_template.json
=> Include discounted duration parameter to outputs of the economic representation

src/constraints/constraint_common.jl, src/run_spineopt_basic.jl, src/util/misc.jl, src/variables/variable_common.jl, src/variables/variable_connection_flow.jl, src/variables/variable_unit_flow.jl, test/variables/variables.jl
=> Fix flow expression bounds

src/util/misc.jl, src/variables/variable_common.jl, src/variables/variable_connection_flow.jl, src/variables/variable_unit_flow.jl, test/variables/variables.jl
=> Fix replacement expressions to work with any number of ins and outs

src/variables/variable_common.jl
=> Fix bound constraint updates

src/data_structure/economic_structure.jl
=> Fix generation of economic representation parameter `tech_discount_factor`

src/run_spineopt_basic.jl
Use threads to save results for each variable/constraint/expression index in parallel.
=> Save results in parallel for each index

src/benders.jl, src/data_structure/preprocess_data_structure.jl, src/run_spineopt_basic.jl, src/util/misc.jl, templates/spineopt_template.json
Introduce report_benders_iters to report results of all iterations.
=> Introduce report benders iters

src/benders.jl, src/run_spineopt.jl
=> Report all benders gaps if reporting iterations

docs/src/advanced_concepts/multi-year.md
=> Minor edit docs

src/benders.jl, src/constraints/constraint_mp_any_invested_cuts.jl, src/constraints/constraint_mp_min_res_gen_to_demand_ratio_cuts.jl, src/data_structure/preprocess_data_structure.jl, src/run_spineopt.jl, src/run_spineopt_basic.jl, src/util/misc.jl, src/util/promise.jl, src/variables/variable_common.jl, src/variables/variable_connections_invested_available.jl, src/variables/variable_storages_invested_available.jl, src/variables/variable_units_invested_available.jl
=> Get rid of internal_fix bounds

src/data_structure/preprocess_data_structure.jl
Add a default value for `min_up_time` and `min_down_time` if the `online_variable_type` is binary or integer.
Fixes #960
=> Add validation for min_up_time and min_down_time

.github/workflows/CompatHelper.yml, .github/workflows/TagBot.yml
Add Tagbot and CompatHelper
Related to #850
=> Prepare for JuliaRegistry

docs/make.jl, docs/src/gallery/gallery.md, docs/src/tutorial/webinars.md
Add new section describing the available examples
Fixes #1103
=> Add new gallery section to the docs

src/data_structure/versions/translate_heatrate_parameters.jl
This update removes unnecessary looping and individual parameter value queries.
=> Improve the efficiency of the heat rate parameter migration script

test/run_spineopt_representative_periods.jl
Added unit test for previously uncovered lines of code.
More specifically, it tests that if it can't find a linear representative index combination then it throws an error.
=> added no_index_found unit test to representative periods test

src/variables/variable_common.jl, test/run_spineopt_representative_periods.jl
=> Don't generate represented variable-expressions if not needed

src/constraints/constraint_common.jl, src/constraints/constraint_connection_flow_capacity.jl, src/constraints/constraint_connection_min_flow.jl, src/constraints/constraint_min_node_state.jl
=> Skip connection min flow if zero lower limit

src/benders.jl, src/constraints/constraint_common.jl, src/run_spineopt.jl, src/run_spineopt_basic.jl
Minor code changes, no functionality changed.
=> Code refactoring
