docs/src/getting_started/installation.md
I think this makes the installation section a bit cleaner, up-to-date, and more consistent with Spine Toolbox User Guide. Please comment if there's something I missed or does not make sense.
=> Update to Installation chapter

src/variables/variable_unit_flow_op.jl, test/constraints/constraint_unit.jl
In one case study, we have a unit that has an operating_point in one direction but not in the other. The previous formulation did not expect a unit to have more than one unit__to_node/from_node relationship. Should be fixed with this merge request
=> Fix unit_flow_op for units with more than one direction

src/data_structure/temporal_structure.jl, src/run_spineopt_sp.jl
- The previous implementation of `in_gaps` conflicted with the representatvie period implementation, should work now
- also: outputs are now written for all (not only representative) days. this way e.g. for unit flow's we get a nicer visualization of the evolution over the entire year
=> Hot fixes bridging gaps

src/constraints/constraint_units_available.jl, test/constraints/constraint_unit.jl
Disclaimer:
Unfortunately, I am a bit pressed for time and don't have time for testing myself. Ideally we would add unit tests e.g. for two-stage stochastic optimization. Current unit tests are passing though. The previous implementation is bugged (see below), so as soon as someone has time to check this, we should merge this quickly.
----
Previously, the investments variable `units_invested_available` would receive the stochastic scenario of the `units_on` variable. However, as investment and operational stochastics are decoupled, different stochastics might be active at different points in time. Now, as we pass all potential paths to the constraint function, we should be able to do this correctly.
=> Bug fix: Include correct stochastic path for this constraint

.github/workflows/ci.yml, Project.toml, src/constraints/constraint_unit_flow_capacity.jl, test/constraints/constraint_unit.jl, test/run_spineopt.jl, test/runtests.jl
This bug was introduced in commit 1a14541933fa0d58189ffb3c5a662dac97e15835 after a series of other adaption. Mainly we summed up the unit_capacity for each unit_flow, while it should be the sum of unit_flows that is constrained by one shared unit_capacity parameter. Bottom line we now retrieve the stochastic scenario for the unit_capacity parameter from the units_on variable again, to restore functionlaity. #483 discusses the problem for other cases
=> Bug fix: restore group capacity functionality

Project.toml, docs/src/library.md, src/SpineOpt.jl, src/data_structure/preprocess_data_structure.jl, src/objective/total_costs.jl, src/run_spineopt.jl, src/run_spineopt_standard.jl, test/Project.toml, test/run_spineopt.jl
Only write to DB at the very end.
This might improve performance of results writing with write-as-roll, since appending to an arrow file should be faster than writing to a Spine DB. Why? Because writing time series or any indexed value to a Spine DB implies reading the value, merging the new data, and then writing the value again. As more and more data is added to the time series, this reading/merging/writing becomes more and more expensive (more data to deal with at each time).
With the arrow technique, we don't need to do the reading/merging part, just the writing. But at the end we need to read from the arrow file, compile and write the time series to the DB as one large chunk, which should be somewhat expensive. We'll see - I think it's good to merge this PR for experimentation with …
=> Write intermediate 'as roll' results to binary files instead of the DB

src/constraints/constraint_connection_flow_lodf.jl, test/constraints/constraint_connection.jl
The lodf constraint now looks like -1 <= post_cont_flow / min_emergency_cap <= 1 
​This PR rewrites it as: -min_emergency_cap <= post_cont_flow <= min_emergency_cap
This way whenever min_emergency_cap is zero we don't have a problem but we rather just constrain the post contingency flow to zero.
=> Avoid division by zero in lodf constraint with outages

test/runtests.jl
...by using isapprox instead of isequal to compare coeffs.
=> Ignore rounding issues in constraint coefficients in tests

docs/src/mathematical_formulation/constraints.md
=> Remove docs on economic lifetime, ramping, and reserves

Project.toml, src/data_structure/temporal_structure.jl, src/run_spineopt_standard.jl, src/variables/variable_common.jl, test/run_spineopt.jl
Re #650
We just fix some issues with using Maps to specify fix_[variable_name] parameter values. It was almost there but needed one extra line of code to include the analysis time in the call to the parameter when fixing the value; as well as one extra line in SpineInterface to interpret nothing as NaN (as the indication that the variable is free in a time-range)
=> Support fixing values using map

docs/src/mathematical_formulation/constraints.md
Bring back the documentation on ramping and reserve constraints
Fixes # 647
=> Bring back documentation on ramps and reserves

Project.toml, src/data_structure/temporal_structure.jl, src/run_spineopt_benders.jl, test/data_structure/temporal_structure.jl
Excluding time slices that go beyond the window to create the history was excluding important time slices. We now include all time slices but make sure none spans beyond...
=> Cut history more properly

src/data_structure/temporal_structure.jl, src/run_spineopt_benders.jl
Temporal blocks shouldn't have gaps, but when building the Benders' master temporal structure we do it by collecting subproblem time slices from different rolling windows. Because temporal blocks might start after the beginning of the window or end before the end, we need to fill the gaps so the collected time slices form a 'solid' temporal block. This PR implements that together with a unit test.
=> Fill master temporal structure per block

src/constraints/constraint_mp_any_invested_cuts.jl, src/constraints/constraint_units_available.jl, src/constraints/constraint_units_invested_available.jl, src/constraints/constraint_units_on.jl, src/objective/renewable_curtailment_costs.jl, src/variables/variable_units_available.jl, test/constraints/constraint_unit.jl
...in constraint_units_on and constraint_units_available.
Fixes #699
=> Get rid of the unit_availability_factor multiplier

src/data_structure/benders_data.jl, src/run_spineopt_standard.jl, src/util/promise.jl
We simplify fixing integer variables by using the fact that the model is a copy, and other stuff, hopefully making it faster.
Also, we set the default value for dual() and reduced_cost() of a promise to zero, so benders doesn't break when the dual is not feasible. Instead, the marginal value will be zero which will impact in the cut for that iteration, and hopefully the algorithm will be able to keep improving the next iteration.
=> Simplify fixing integers vars

src/constraints/constraint_mp_any_invested_cuts.jl, src/data_structure/benders_data.jl, src/data_structure/preprocess_data_structure.jl, src/run_spineopt_standard.jl, test/run_spineopt_benders.jl
Previously, we were computing the marginal value of the unit investments as the reduced cost of the units_on variable. This is a bit non-intuitive - it should be the reduced cost of units_invested_available.
But units_invested_available didn't work for us reliably, and I think I just found out why:
when computing the duals, if units_on was discrete in the original problem, we would fix its value in the relaxed problem. That means additional investments wouldn't be usable (because the units_on was already fixed) resulting in reduced cost of units_invested_available being zero.
This commit rationalizes the whole thing. The marginal value of the unit investments is obtained from the reduced cost of units_invested_available, as it should be. To avoid it being zero, we don't fix discrete …
=> Fix duals calculation for Benders

Project.toml, src/SpineOpt.jl, src/constraints/constraint_unit_flow_op_bounds.jl, src/constraints/constraint_units_available.jl, test/runtests.jl
This pull request addresses the `Parameter` and `parameter_value` name conflict with SpineInterface in JuMP v1.14 and higher. Resolving the name conflict wasn't terribly difficult, but there are a few odd errors remaining.
Fixes #745 (eventually?)
=> WIP Resolve JuMP `Parameter` and `parameter_value` conflicts

docs/src/mathematical_formulation/constraints.md, docs/src/mathematical_formulation/constraints_automatically_generated_file.md
This is related to issue #654, PR #742. 
PR #742 changed the constraint minimum operating point, but the docs were not correctly written. This PR fix the doc.
=> Fix doc constraint minimum operating point

docs/src/advanced_concepts/ramping.md, docs/src/advanced_concepts/reserves.md, docs/src/tutorial/reserves.md
This pull request updates the reserve tutorial link in the documentation to use the correct markdown syntax.
Fixes #829
=> Update reserve tutorial link in documentation

src/constraints/constraint_unit_flow_capacity.jl, src/util/misc.jl
Turn a duration of `Month` or `Year` into `Day` anchored to the "active" `TimeSlice` used by the function that needs the duration.
Fixes #838
=> resolve duration comparison conflicts

Project.toml, examples/reserves.json, examples/simple_system.json, examples/unit_commitment.json, examples/upgrade_all.jl, src/run_spineopt.jl, test/run_examples.jl
Also upgrade examples json to latest structure.
=> Remove PyCall dependency to run_spineopt with a Dict

docs/src/getting_started/installation.md
The links for Spine Toolbox and SpineOpt were inverted
Fixes NA
=> Fix installation links in the docs

src/constraints/constraint_node_injection.jl, src/data_structure/temporal_structure.jl, src/variables/variable_common.jl, test/data_structure/temporal_structure.jl
Previously, if the same t was represented by more than one representative ts, only the last one processed would stay, leading to bugs. Now we fix that and also help the user in case they created a mapping for a temporal block but forgot to associate the
representative temporal block with their node or unit.
=> Improve treatment of representative time slices

src/run_spineopt.jl, src/run_spineopt_benders.jl, src/run_spineopt_standard.jl
This is so we can have more than one callback.
It allows for more customization, notably to add user callbacks on top of already existing e.g. Benders callbacks.
=> Register window about to solve/solved callbacks in model ext

src/data_structure/benders_data.jl, src/run_spineopt.jl, src/run_spineopt_benders.jl, src/run_spineopt_standard.jl
This is to avoid double counting when the kernel is called in a loop by a third party kernel used as replacement.
=> Make sure the sp obj val computation starts at zero for the first window

src/data_structure/postprocess_results.jl
In the original code, it is assumed the `connection__from_node` contains at least 2 `node`s, which could not be the case where a connection has only single direction. Unless I misunderstand the function for saving the average through flow, changes are made to fetch the 2nd `node` `n_to` from `connection__to_node`.
Fixes #927
=> Attempt to fix the issue #927

.github/workflows/ci.yml
Update Julia version in CI workflow to test the latest release of Julia v1.x
Fixes # 932
=> Update Julia version in CI workflow

benchmark/Project.toml, benchmark/benchmarks.jl
Create a benchmark script.
@manuelma @Tasqu, @suvayu and I created this simple benchmark using the first test in run_spineopt.jl.
However, this is not substantial enough.
Can you
- suggest improvements to make it more substantial; and/or
- share some data in sqlite format?
Thanks in advance.
=> Create benchmark script

src/constraints/constraint_common.jl, src/constraints/constraint_connection_intact_flow_ptdf.jl, src/constraints/constraint_node_injection.jl, src/constraints/constraint_ratio_unit_flow.jl, src/constraints/constraint_unit_flow_capacity.jl, src/data_structure/stochastic_structure.jl, src/data_structure/temporal_structure.jl, src/expressions/capacity_margin.jl, test/data_structure/stochastic_structure.jl
This PR (together with a recent commit to SpineInterface) improves the algorithm to compute the low/highest resolution time slices in a set. Before, for each time slice we would look at all the others to see if it contained/was contained in the other. This has a complexity of order n square, leading to quick performance degration with the number of time slices. Now we rely on ordering/grouping time slices by duration to achieve near order n performance.
I tested Yi's PyPSA model and the 1 year run now completes in about 2 minutes and a half instead of the 10 minutes previously reported.
Re #855
=> Performance optimisation

examples/reserves.json, examples/simple_system.json, examples/unit_commitment.json, test/run_examples.jl
To maintain consistency in the objective function of our examples, we add it to the test. We use a dictionary to select the examples we want to test the objective function for, or simply check if it's optimal.
Fixes #935
=> Add the objective function of the examples to the tests in run examples.jl

docs/src/library.md, src/SpineOpt.jl, src/data_structure/temporal_structure.jl, src/run_spineopt.jl, src/run_spineopt_benders.jl, src/run_spineopt_standard.jl
- Remove benders master problem events, users can hook to normal events on the master model object itself.
- Expose prepare_spineopt and run_spineopt!
- Don't rebuild the model if already built, this way users can really reuse the same `m` in multiple calls to run_spineopt!
=> Improve extension mechanism once more

src/constraints/constraint_minimum_operating_point.jl, src/constraints/constraint_operating_point_bounds.jl, src/constraints/constraint_ratio_unit_flow.jl, src/constraints/constraint_unit_flow_capacity.jl, src/constraints/constraint_unit_flow_op_bounds.jl, src/constraints/constraint_unit_state_transition.jl, src/constraints/constraint_units_available.jl, src/constraints/constraint_units_out_of_service_transition.jl, src/data_structure/preprocess_data_structure.jl, src/expressions/capacity_margin.jl, src/variables/variable_units_on.jl, src/variables/variable_units_out_of_service.jl, test/constraints/constraint_node.jl, test/constraints/constraint_unit.jl, test/expressions/expression.jl, test/run_spineopt.jl
Only creates units_on, units_started_up, units_started_up, units_out_of_service, units_taken_out_of_service, and units_returned_to_service if needed.
=> Only create unit variables if needed

src/constraints/constraint_connection_flow_capacity.jl, src/constraints/constraint_nodal_balance.jl, src/constraints/constraint_node_injection.jl, src/constraints/constraint_ratio_unit_flow.jl, src/constraints/constraint_unit_flow_capacity.jl
The idea is to use Base.get and Base.haskey to check for indices instead of double dipping into the indices functions.
I did it for some constraints but the same idea could be applied to a lot of constraints for a mild speed up.
=> Avoid double dipping into indices functions

src/data_structure/preprocess_data_structure.jl, src/variables/variable_connection_flow.jl, src/variables/variable_connection_intact_flow.jl, src/variables/variable_node_state.jl, src/variables/variable_unit_flow.jl, src/variables/variable_unit_flow_op.jl
Some variable indices functions were collecting the temporal block twice so to say.
=> Performance: don't collect time indices twice

src/constraints/constraint_mp_min_res_gen_to_demand_ratio_cuts.jl, src/data_structure/stochastic_structure.jl
New short-circuit to skip any lookups for deterministic models, we just return the single scenario every time.
=> Performance: Optimise stochastic index generation for deterministic models

src/constraints/constraint_ratio_out_in_connection_flow.jl, src/constraints/constraint_ratio_unit_flow.jl, src/run_spineopt_standard.jl, src/util/misc.jl, src/variables/variable_binary_gas_connection_flow.jl, src/variables/variable_common.jl, src/variables/variable_connection_flow.jl, src/variables/variable_unit_flow.jl, test/run_examples.jl
In the most simple case where we have `unit_flow[from_node] == ratio * unit_flow[to_node]`, we actually can use just one flow variable and replace the constraint by an expression. This should save some time.
So in the example above we can have `unit_flow[to_node]` pointing to a variable, and `unit_flow[from_node]` pointing to the expression `ratio * that_variable`.
=> Introduce simple fix ratios

src/constraints/constraint_connection_flow_capacity.jl, src/variables/variable_connection_flow.jl, src/variables/variable_storages_invested_available.jl, test/constraints/constraint_connection.jl
=> Performance: Use upper bound for connection flow instead of the connection capacity constraint when possible

src/data_structure/temporal_structure.jl
This PR solves an issue where node state transition was not enforced across temporal blocks - so in the boundary between two blocks it was allowed to jump freely.
=> Fix dynamic time indices when two blocks are involved

src/data_structure/temporal_structure.jl, src/run_spineopt_basic.jl, src/util/misc.jl, src/variables/variable_common.jl, src/variables/variable_connection_flow.jl, src/variables/variable_node_state.jl, src/variables/variable_unit_flow.jl
As per title, FlexParameter is not needed and introduces a round-about. This PR eliminates it.
=> Get rid of FlexParameter

.github/workflows/ci.yml, Project.toml, README.md, src/constraints/constraint_common.jl, src/constraints/constraint_connection_lifetime.jl, src/constraints/constraint_min_down_time.jl, src/constraints/constraint_min_scheduled_outage_duration.jl, src/constraints/constraint_min_up_time.jl, src/constraints/constraint_ratio_out_in_connection_flow.jl, src/constraints/constraint_storage_lifetime.jl, src/constraints/constraint_unit_lifetime.jl, src/constraints/constraint_units_out_of_service_contiguity.jl, test/constraints/constraint_unit.jl, test/run_spineopt_mga.jl, test/runtests.jl
This PR improves the auto-update system so it also can update constraints that include terms depending on the value of a parameter value, for example min_up_time. Now if the value of min_up_time changes across different model solves, the constraint includes just the right terms.
IMPORTANT: SpineOpt now requires Julia >= 1.8 to be able to use ifelse with 'calls'.
=> Auto update constraints that need to look behind

src/constraints/constraint_connection_flow_capacity.jl, src/data_structure/preprocess_data_structure.jl, src/data_structure/temporal_structure.jl, src/util/misc.jl, test/run_spineopt.jl
Minor refactoring to avoid operating with parameter values in preprocessing. It's better to juts access values once the model is built because of as_number and as_call.
=> Get rid of flow capacity

src/data_structure/preprocess_data_structure.jl, src/variables/variable_common.jl, src/variables/variable_units_on.jl, src/variables/variable_units_out_of_service.jl, src/variables/variable_units_returned_to_service.jl, src/variables/variable_units_shut_down.jl, src/variables/variable_units_started_up.jl, src/variables/variable_units_taken_out_of_service.jl, test/constraints/constraint_unit.jl
Recently we implemented a mechanism to skip online and outage variables based on the values of some parameters - so we don't generate variables that are not needed. This PR uses that same mechanism to implement the online_variable_type_none thing.
=> Get rid of replacement_value

src/constraints/constraint_min_scheduled_outage_duration.jl, src/constraints/constraint_units_out_of_service_contiguity.jl, test/constraints/constraint_unit.jl
We make it a range constraint so the sum of units_out_of_service over the window is greater than the scheduled outage duration but also lower than the scheduled outage duration plus the maximum error due to the temporal resolution of the unit not being able to fit exactly the scheduled outage duration.
=> Tighten up min_scheduled_outage_duration constraint

src/constraints/constraint_ratio_unit_flow.jl, src/util/misc.jl, src/variables/variable_unit_flow.jl, src/variables/variable_units_on.jl, test/constraints/constraint_unit.jl, test/variables/variables.jl
Support start_flow in fix_ratio_unit_flow constraints.
=> Start flow

src/constraints/constraint_common.jl
Months and Years are challenging for detailed comparisons in the package Dates, since they don't have an exact length as the number of days varies in both. E.g. every leap year is longer than 365 days, so Dates doesn't allow direct comparisons with ill-defined durations as a precaution.
These changes take the parameter and convert it into days if it is defined as a duration in years or months. It will use a standard value of 365 and 30 days for each one.
Fixes #1038
=> Convert duration to days for past indices calculation

docs/src/concept_reference/fix_connection_flow.md
=> Add free energy warning to docs

docs/src/how_to/print_the_model.md
Include extra instructions on how to print the complete model using the JuMP function.
Fixes #1043
=> Add instructions for printing the model to a file

examples/stochastic.json
Originally stochastic.json belonging to the stochastic tutorial did not have an extension. That is how it bypassed the tests. When the extension was corrected, it did cause errors. There seems to be an issue with the DAG of the extended tutorial. The tutorial does not explicitly cover this part so for now it is ok to remove the additional part.
=> bugfix database stochastic tutorial

src/run_spineopt_basic.jl
The output for the `_discounted_duration` should now use the flow indices instead of the investment ones. 
Fixes #1072
=> Calculate the `_discounted_duration` outputs with the flow indices

src/benders.jl, src/data_structure/temporal_structure.jl, src/run_spineopt_basic.jl, src/run_spineopt_mga.jl, src/variables/variable_common.jl, test/run_spineopt.jl, test/run_spineopt_mga.jl, test/run_spineopt_multi_stage.jl
Improve saving outputs by pushing work to the report writing phase rather than repeating it for every rolling window.
Similarly, improve fixing history by pulling work to the variable creation phase (rather than repeating it for every rolling window).
Also, don't save outputs until Benders converges. This requires doing an extra iteration after the algorithm terminated just to collect the outputs.
=> Improve saving outputs and fixing history

src/objective/fixed_om_costs.jl, test/objective/objective.jl
Using `units_invested_available_indices` in the function `fixed_om_costs` to avoid errors when using the representative periods feature.
Fixes #1122
=> Change indices function in the fixed_om_costs function

src/objective/fixed_om_costs.jl, test/objective/objective.jl
Reverts spine-tools/SpineOpt.jl#1123 to improve commit tracking
=> Revert "Change indices function in the fixed_om_costs function"

docs/src/getting_started/troubleshooting.md, docs/src/how_to/change_the_solver.md
This pull request includes updates to the documentation to address a common solver error and provide guidance on changing solver parameters in SpineOpt.
Documentation updates:
* [`docs/src/getting_started/troubleshooting.md`](diffhunk://#diff-71f97fe067e112765767b69ec61531216040d3f04c918ab8e5773d408e019d44R11-R15): Added a new section to address the "Name too long" error thrown by solvers and provided a solution using solver parameters.
* [`docs/src/how_to/change_the_solver.md`](diffhunk://#diff-f6e131ab1bfed54bece1555437c1d583a22e10a29331c98e4e7abc692fb1d73aL1-R1): Updated the header to include an encoded reference for easier navigation within the documentation.
Fixes #1126
=> Add troubleshooting for long names in the solver

src/data_structure/economic_structure.jl
=> Apply review suggestions for economic representation calculation

docs/make.jl, docs/src/getting_started/performance_tips.md, src/run_spineopt.jl, test/data_structure/temporal_structure.jl
Following the performance tips from [JuMP docs](https://jump.dev/JuMP.jl/stable/tutorials/getting_started/performance_tips/#Performance-tips), this PR implements the following option in the `run_spineopt` function:
- `use_model_names`(default = `true`): whether or not to create the model with names
- `add_bridges`(default = `false`): whether or not bridges from JuMP to the solver should be added to the model
**Notes**
- The `use_model_names` default is equal to `true`, so the users can gain more speed when creating the model by setting this option to `false`.
- The `add_bridges` option is set to `true` for the MGA algorithm, since it is necessary to run that feature.
Fixes #1148
=> Add options to improve model creation speed

src/constraints/constraint_common.jl
Reusing the function `align_variable_duration_unit` instead of creating a new one `convert_to_days`
Fixes #1152
=> Use `align_variable_duration_unit` function instead of `convert_to_days`

src/constraints/constraint_node_injection.jl
A quick and temporal fix to #1150 before the epic 0.7.2x-release gets merged.
Help the case using some sample operational temporal blocks (not necessary representative periods)
=> constraint_node_injection to align with representative time slices

.github/workflows/Test.yml
Changes in spine db api should trigger SpineOpt tests to ensure that spine tools still work. The trigger in spine db api requires a new test file in SpineOpt. That file is heavily inspired by a similar test for SpineInterface.
=> trigger test for spine db api

.install_spinedb_api.jl
Needed to force unit tests to use the correct `spinedb_api` Git branch when the tests are called from Spine-Database-API repository.
No associated issue.
=> Make .install_spinedb_api.jl accept spinedb_api Git ref as command line argument

src/constraints/constraint_common.jl, src/run_spineopt_basic.jl, test/run_spineopt_representative_periods.jl
1. draft unit_tests for `min_up/down_time` constraints
2. prevent activating multi-threading when it is not intended
Fixes #1176
=> Attempt to fix/resolve the representative_periods tests issues

src/constraints/constraint_common.jl, src/constraints/constraint_connection_flow_capacity.jl, src/constraints/constraint_min_down_time.jl, src/constraints/constraint_min_scheduled_outage_duration.jl, src/constraints/constraint_units_available.jl, src/generate_forced_outages.jl, src/objective/fixed_om_costs.jl, src/variables/variable_node_state.jl, src/variables/variable_unit_flow.jl, src/variables/variable_units_on.jl, test/objective/objective.jl
=> default `number_of_units` for non-investable and investable units

src/objective/fixed_om_costs.jl
spotted by @kkozersk: every objective term is supposed to have a corresponding scenario weight
=> add scenario weights to fom cost

src/data_structure/economic_structure.jl, test/data_structure/check_economic_structure.jl
Give default values for economic parameters to ensure that they can be saved without errors.
=> Set default values for economic parameters

examples/capacity_planning.json, examples/multi-year_investment_with_econ_params_with_milestones.json, examples/multi-year_investment_with_econ_params_without_milestones.json, examples/multi-year_investment_without_econ_params.json, examples/reserves.json, examples/rolling_horizon.json, examples/simple_system.json, examples/stochastic.json, examples/unit_commitment.json, src/data_structure/migration.jl, templates/spineopt_template.json
Change spineopt_template.json version number to 16 and update the migration scripts so that the newest template is loaded.
=> Update migration scripts and the template version number

examples/capacity_planning.json, examples/multi-year_investment_with_econ_params_with_milestones.json, examples/multi-year_investment_with_econ_params_without_milestones.json, examples/multi-year_investment_without_econ_params.json, examples/reserves.json, examples/rolling_horizon.json, examples/simple_system.json, examples/stochastic.json, examples/unit_commitment.json, src/constraints/constraint_node_state_capacity.jl, src/data_structure/preprocess_data_structure.jl, src/variables/variable_node_state.jl, templates/spineopt_template.json, test/constraints/constraint_node.jl
The key changes include the addition of a new `node_availability_factor` parameter for nodes and updating the unit capacity constraint accordingly.
* **Renaming and Refactoring:**
- Renamed the function `node_state_cap` to `node_state_capacity` for improved clarity and consistency across the codebase. This change affects its usage in `constraint_node_state_capacity.jl` and `variable_node_state.jl`.
* **New Parameter:**
- Added a new parameter `node_availability_factor` in the `spineopt_template.json` file. This parameter acts as a multiplier (typically between 0 and 1) on the `node_state_capacity`, representing the availability of a node.
* **New Preprocessing Function:**
- Introduced a new function `generate_node_state_capacity()` in `preprocess_data_structure.jl`. This function …
=> Add the node availability factor to the model

src/constraints/constraint_min_node_state.jl
This pull request updates the logic and documentation for the `constraint_min_node_state` functionality in the `src/constraints/constraint_min_node_state.jl` file. The changes ensure that constraints are only generated when relevant conditions are met, improving efficiency and clarity.
=> Add parameter function `node_state_lower_limit` to the indices function of the minimum node state

examples/capacity_planning.json, examples/multi-year_investment_with_econ_discounting_consecutives.json, examples/multi-year_investment_with_econ_discounting_milestones.json, examples/multi-year_investment_without_econ_discounting.json, examples/reserves.json, examples/rolling_horizon.json, examples/simple_system.json, examples/stochastic.json, examples/unit_commitment.json, src/data_structure/migration.jl, src/data_structure/versions/translate_use_economic_representation__use_milestone_years.jl, templates/spineopt_template.json, test/data_structure/migration.jl
This pull request updates the SpineOpt data structure version across multiple example files and introduces two new migration functions to ensure compatibility with the latest template.
* Updated the `settings.version` in the SpineOpt template file `templates/spineopt_template.json` to version `18`.
* Updated the `settings.version` from `16` to `18` in multiple example files to reflect the latest SpineOpt data structure version:
* Added a new function `add_node_availability_factor` in `src/data_structure/migration.jl` to ensure the latest template is loaded.
* Added a new function `translate_use_economic_representation__use_milestone_years` and included it in `src/data_structure/migration.jl` to ensure migration to the compatible data structure.
* Added unit tests corresponding to the …
=> Update migration script and SpineOpt DB version

src/run_spineopt_basic.jl
Changed 'for' loops to 'map' to remove a bottleneck. 
The code is very similar but note that I have changed a dictionary to a vector of pairs with [collect()](https://docs.julialang.org/en/v1/base/iterators/#Base.Iterators.map). \[Edit: not anymore, it's a dictionary again :)]
=> Up to 7x faster _save_outputs!()

examples/capacity_planning.json, examples/multi-year_investment_with_econ_discounting_consecutives.json, examples/multi-year_investment_with_econ_discounting_milestones.json, examples/multi-year_investment_without_econ_discounting.json, examples/reserves.json, examples/rolling_horizon.json, examples/simple_system.json, examples/stochastic.json, examples/unit_commitment.json, src/data_structure/migration.jl, src/data_structure/versions/translate_use_economic_representation__use_milestone_years.jl, templates/spineopt_template.json, test/data_structure/migration.jl
Renew PR #1205 to fix issue #1222
=> Update migration script

src/data_structure/economic_structure.jl, src/data_structure/preprocess_data_structure.jl, src/objective/fixed_om_costs.jl, test/data_structure/check_economic_structure.jl, test/run_spineopt_benders.jl
- Fixes the calculation of `fixed_om_cost` under the economic discounting setup.
- Spontaneously fixes the Benders unit test for storage
- Add (retrieve) the creation of `units_on` variable triggered by defining `units_on_coefficient` parameter
DB: [discounted-multi-year-invest.json](https://github.com/user-attachments/files/20692269/discounted-multi-year-invest.json)
- basic: fom_cost = vom_cost = 1, demand = capacity = 100, all discounting rates = 0
- temporal structure: investment: 2000-2005 (5Y), 2006 (1Y); operation (milestone year 2000): 4M
- fixed_om_costs = 1\*100\*(8784\*5+8760\*1) = 5,268,000
- variable_om_costs = 1\*100\*[ 4M\*5\*3`(for year 2000)` + 4M\*1\*3`(for year 2006)`] = 5,268,000
whereas in the existing calculation: fixed_om_costs = …
=> Fix economic discounting duration
